"""BotTrade Python SDK."""

from .agents import (
    AsyncDecidingAgent,
    DecidingAgent,
    buy,
    cover,
    hold,
    sell,
    short,
)
from .client import (
    DEFAULT_API_URL,
    DEFAULT_MCP_URL,
    AsyncBotTradeClient,
    BotTradeClient,
    RetryPolicy,
)
from .errors import (
    AgentExecutionError,
    APIError,
    AuthenticationRequired,
    BotTradeError,
    IncompleteRunError,
    PublicationConfirmationRequired,
)
from .models import (
    AgentInfo,
    Bar,
    Decision,
    Fill,
    MarketObservation,
    Observation,
    Order,
    Position,
    PublicRun,
    QueuedOrder,
    Results,
    Run,
    RunSnapshot,
    Scenario,
    StepResult,
)
from .session import BacktestSession, session
from .workflows import (
    BacktestResult,
    BenchmarkOutcome,
    backtest,
    backtest_async,
    format_results,
    require_completed_results,
    run,
    run_buy_and_hold,
)

__all__ = [
    "DEFAULT_API_URL",
    "DEFAULT_MCP_URL",
    "APIError",
    "AgentExecutionError",
    "AgentInfo",
    "AsyncBotTradeClient",
    "AsyncDecidingAgent",
    "AuthenticationRequired",
    "BacktestResult",
    "BacktestSession",
    "Bar",
    "BenchmarkOutcome",
    "BotTradeClient",
    "BotTradeError",
    "DecidingAgent",
    "Decision",
    "Fill",
    "IncompleteRunError",
    "MarketObservation",
    "Observation",
    "Order",
    "Position",
    "PublicRun",
    "PublicationConfirmationRequired",
    "QueuedOrder",
    "Results",
    "RetryPolicy",
    "Run",
    "RunSnapshot",
    "Scenario",
    "StepResult",
    "backtest",
    "backtest_async",
    "buy",
    "cover",
    "format_results",
    "hold",
    "require_completed_results",
    "run",
    "run_buy_and_hold",
    "sell",
    "session",
    "short",
]

__version__ = "0.2.0"
